sudo: required

services:
  - docker

before_install: 
  - docker build -t espressotrip/docker-ci-workflow -f Dockerfile.dev .

script:
  - docker run espressotrip/docker-ci-workflow npm run test -- --watchAll=false


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-383606148519"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
